### REQUEST DE USERS (TODOS)
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "rut": "18.758.889-2",
    "name": "Camilein",
    "lastName": "Pino",
    "email": "camilos@email.com",
    "password": "123456",
    "role": "client",
    "birthday": "1994-11-08",
    "gender": "M",
    "description": "Hola",
    "phone": "123456789"
}

### Request para buscar todos los usuarios
GET http://localhost:9000/api/users HTTP/1.1

### Request para buscar un usuarios por id
GET http://localhost:9000/api/users/63951390efdbc449fb26f7ec HTTP/1.1

### Request para cambiar datos de usuarios por id
PUT http://localhost:9000/api/users/6394fefa64ec92f824122b8c HTTP/1.1
Content-Type: application/json

{
    "rut": "18.758.889-8",
    "name": "Juan",
    "lastName": "Pino",
    "email": "camilo@email.com",
    "password": "123456"
}

### Request para eliminar un usuario por id
DELETE http://localhost:9000/api/users/639513dcefdbc449fb26f7f5  HTTP/1.1

### REQUEST DE USERS (CLIENTES)

###
POST http://localhost:9000/api/users/clients HTTP/1.1
Content-Type: application/json

{
    "rut": "18.758.777-6",
    "name": "Camilein",
    "lastName": "Pino",
    "email": "camilosos@email.com",
    "password": "123456",
    "birthday": "1994-11-08",
    "gender": "M",
    "description": "Hola",
    "phone": "123456789"
}

### Request para buscar todos los clientes
GET http://localhost:9000/api/users/clients HTTP/1.1

// REQUEST DE CLIENT

### Request para ingresar un cliente
POST http://localhost:9000/api/clients HTTP/1.1
Content-Type: application/json

{
    "rut": "18.758.889-8",
    "name": "Camilein",
    "lastName": "Pino",
    "email": "camilo@email.com",
    "password": "123456"
}

### Request para buscar todos los clientes
GET http://localhost:9000/api/clients HTTP/1.1

### Request para buscar un cliente por id
GET http://localhost:9000/api/clients/6392b4474b0dc2f51762582b HTTP/1.1

### Request para cambiar datos por id
PUT http://localhost:9000/api/clients/6392b3e94b0dc2f517625829 HTTP/1.1
Content-Type: application/json

{
    "rut": "18.758.889-8",
    "name": "Camilein",
    "lastName": "Pino",
    "email": "camilo@email.com",
    "password": "123456"
}

### Request para eliminar un cliente por id
DELETE http://localhost:9000/api/clients/6392b3e94b0dc2f517625829 HTTP/1.1

### Request para cambiar datos por id
PUT http://localhost:9000/api/clients/6392b4474b0dc2f51762582b HTTP/1.1
Content-Type: application/json

{
    "rut": "18.569.695-9",
    "name": "Kevin",
    "lastName": "Cruz",
    "email": "kevincruz@email.com",
    "password": "123456"
}


//****************************************************************************************************
//REQUESTS PARA ADMINISTRADORES

### Request para agregar un ADMIN 
POST http://localhost:9000/api/admins HTTP/1.1
Content-Type: application/json

{
    "rut": "18.758.889-8",
    "name": "Camilein",
    "lastName": "Pino",
    "email": "camilo@email.com",
    "password": "123456"
}

### Request para buscar todos los ADMIN
GET http://localhost:9000/api/admins HTTP/1.1

### Request para buscar un ADMIN por id
GET http://localhost:9000/api/admins/6393d579e337d6956b1af3f3 HTTP/1.1


### Request para eliminar un ADMIN por id
DELETE http://localhost:9000/api/admins/6393d5322a480af15566439c HTTP/1.1

### Request para cambiar datos de ADMIN por id
PUT http://localhost:9000/api/admins/6393d579e337d6956b1af3f3 HTTP/1.1
Content-Type: application/json

{
    "rut": "18.569.695-9",
    "name": "Kevin",
    "lastName": "Cruz",
    "email": "kevincruz@email.com",
    "password": "123456"
}